import { CATEGORIES } from "./constants";

export type SeedSolicitud = {
  client_email: string;
  category: (typeof CATEGORIES)[number];
  brand: string | null;
  model: string | null;
  year: number | null;
  storage: string | null;
  condition: string | null;
  description: string | null;
  expected_amount_pen: number;
  expected_term_days: number;
  district: string;
  status: "active" | "accepted" | "closed" | "expired";
};

export const SOLICITUDES: SeedSolicitud[] = [
  // ── celular (6) ──────────────────────────────────────────────────────────
  {
    client_email: "cliente1@empenalo.test",
    category: "celular",
    brand: "Apple",
    model: "iPhone 14 Pro",
    year: 2023,
    storage: "256 GB",
    condition: "Bueno",
    description: "Ligero rayón en marco superior. Pantalla y batería perfectas.",
    expected_amount_pen: 2500,
    expected_term_days: 30,
    district: "Miraflores",
    status: "active",
  },
  {
    client_email: "cliente2@empenalo.test",
    category: "celular",
    brand: "Samsung",
    model: "Galaxy S23 Ultra",
    year: 2023,
    storage: "256 GB",
    condition: "Bueno",
    description: "Mica desde día uno. Cargador original incluido.",
    expected_amount_pen: 2100,
    expected_term_days: 30,
    district: "San Isidro",
    status: "active",
  },
  {
    client_email: "cliente3@empenalo.test",
    category: "celular",
    brand: "Apple",
    model: "iPhone 13 Pro Max",
    year: 2022,
    storage: "128 GB",
    condition: "Regular",
    description: "Batería al 82%. Funciona perfecto.",
    expected_amount_pen: 1600,
    expected_term_days: 30,
    district: "Santiago de Surco",
    status: "active",
  },
  {
    client_email: "cliente6@empenalo.test",
    category: "celular",
    brand: "Xiaomi",
    model: "13T Pro",
    year: 2023,
    storage: "512 GB",
    condition: "Nuevo",
    description: "Desempaquetado pero sin uso. Plásticos puestos.",
    expected_amount_pen: 1500,
    expected_term_days: 30,
    district: "Miraflores",
    status: "active",
  },
  {
    client_email: "cliente5@empenalo.test",
    category: "celular",
    brand: "Google",
    model: "Pixel 8 Pro",
    year: 2023,
    storage: "256 GB",
    condition: "Bueno",
    description: "Caja original. Sin detalles visibles.",
    expected_amount_pen: 1900,
    expected_term_days: 30,
    district: "La Molina",
    status: "accepted",
  },
  {
    client_email: "cliente8@empenalo.test",
    category: "celular",
    brand: "Apple",
    model: "iPhone 15",
    year: 2024,
    storage: "128 GB",
    condition: "Nuevo",
    description: "Sellado. Garantía Apple vigente 11 meses.",
    expected_amount_pen: 2800,
    expected_term_days: 45,
    district: "Surquillo",
    status: "active",
  },

  // ── laptop (4) ───────────────────────────────────────────────────────────
  {
    client_email: "cliente2@empenalo.test",
    category: "laptop",
    brand: "Apple",
    model: 'MacBook Pro M2 14"',
    year: 2023,
    storage: "512 GB SSD",
    condition: "Nuevo",
    description: "Comprado hace 3 meses. Factura. Garantía.",
    expected_amount_pen: 5500,
    expected_term_days: 60,
    district: "San Isidro",
    status: "active",
  },
  {
    client_email: "cliente1@empenalo.test",
    category: "laptop",
    brand: "Dell",
    model: "XPS 13 Plus",
    year: 2022,
    storage: "1 TB SSD",
    condition: "Bueno",
    description: "Pantalla OLED. Teclado táctil. Cuidada.",
    expected_amount_pen: 3200,
    expected_term_days: 30,
    district: "Miraflores",
    status: "active",
  },
  {
    client_email: "cliente4@empenalo.test",
    category: "laptop",
    brand: "Lenovo",
    model: "ThinkPad X1 Carbon",
    year: 2022,
    storage: "512 GB SSD",
    condition: "Bueno",
    description: "Empresarial. Batería excelente.",
    expected_amount_pen: 2800,
    expected_term_days: 45,
    district: "San Borja",
    status: "closed",
  },
  {
    client_email: "cliente7@empenalo.test",
    category: "laptop",
    brand: "Asus",
    model: "ROG Zephyrus G14",
    year: 2023,
    storage: "1 TB SSD",
    condition: "Bueno",
    description: "Gaming. RTX 4060. Cargador original.",
    expected_amount_pen: 4200,
    expected_term_days: 60,
    district: "Barranco",
    status: "active",
  },

  // ── joya (4) ─────────────────────────────────────────────────────────────
  {
    client_email: "cliente3@empenalo.test",
    category: "joya",
    brand: null,
    model: "Anillo oro 18k",
    year: null,
    storage: null,
    condition: "Bueno",
    description: "Anillo de compromiso. 5.2 g. Con tasación reciente.",
    expected_amount_pen: 1800,
    expected_term_days: 30,
    district: "Santiago de Surco",
    status: "active",
  },
  {
    client_email: "cliente5@empenalo.test",
    category: "joya",
    brand: null,
    model: "Cadena oro 14k",
    year: null,
    storage: null,
    condition: "Bueno",
    description: "Cadena 50 cm. 12 g. Sin daños.",
    expected_amount_pen: 1400,
    expected_term_days: 30,
    district: "La Molina",
    status: "active",
  },
  {
    client_email: "cliente1@empenalo.test",
    category: "joya",
    brand: null,
    model: "Pulsera oro 18k con diamantes",
    year: null,
    storage: null,
    condition: "Nuevo",
    description: "Diamantes naturales. Certificado GIA.",
    expected_amount_pen: 3500,
    expected_term_days: 60,
    district: "Miraflores",
    status: "accepted",
  },
  {
    client_email: "cliente6@empenalo.test",
    category: "joya",
    brand: null,
    model: "Aretes oro blanco",
    year: null,
    storage: null,
    condition: "Bueno",
    description: "Par de aretes. 4 g cada uno.",
    expected_amount_pen: 900,
    expected_term_days: 30,
    district: "Miraflores",
    status: "active",
  },

  // ── reloj (3) ────────────────────────────────────────────────────────────
  {
    client_email: "cliente2@empenalo.test",
    category: "reloj",
    brand: "Rolex",
    model: "Submariner Date",
    year: 2020,
    storage: null,
    condition: "Bueno",
    description: "Acero. Papeles originales. Servicio reciente.",
    expected_amount_pen: 12000,
    expected_term_days: 60,
    district: "San Isidro",
    status: "active",
  },
  {
    client_email: "cliente4@empenalo.test",
    category: "reloj",
    brand: "Tag Heuer",
    model: "Carrera Caliber 16",
    year: 2021,
    storage: null,
    condition: "Bueno",
    description: "Cronógrafo automático. Funcionamiento perfecto.",
    expected_amount_pen: 3800,
    expected_term_days: 45,
    district: "San Borja",
    status: "active",
  },
  {
    client_email: "cliente8@empenalo.test",
    category: "reloj",
    brand: "Omega",
    model: "Seamaster Diver 300M",
    year: 2022,
    storage: null,
    condition: "Nuevo",
    description: "Caja y papeles. Garantía Omega vigente.",
    expected_amount_pen: 9500,
    expected_term_days: 60,
    district: "Surquillo",
    status: "expired",
  },

  // ── electrodomestico → otro (3) ───────────────────────────────────────────
  {
    client_email: "cliente5@empenalo.test",
    category: "otro",
    brand: "LG",
    model: "Refrigeradora No Frost 410 L",
    year: 2022,
    storage: null,
    condition: "Bueno",
    description: "InstaView. Funcionando perfecto. Factura.",
    expected_amount_pen: 1500,
    expected_term_days: 30,
    district: "La Molina",
    status: "active",
  },
  {
    client_email: "cliente7@empenalo.test",
    category: "otro",
    brand: "Samsung",
    model: 'Smart TV 55" QLED',
    year: 2023,
    storage: null,
    condition: "Nuevo",
    description: "Caja sellada. Recibida como regalo.",
    expected_amount_pen: 1700,
    expected_term_days: 30,
    district: "Barranco",
    status: "active",
  },
  {
    client_email: "cliente3@empenalo.test",
    category: "otro",
    brand: "Bosch",
    model: "Lavadora 9 kg",
    year: 2021,
    storage: null,
    condition: "Bueno",
    description: "Programa eco. Excelente estado.",
    expected_amount_pen: 1100,
    expected_term_days: 30,
    district: "Santiago de Surco",
    status: "closed",
  },

  // ── videojuego → otro (3) ─────────────────────────────────────────────────
  {
    client_email: "cliente6@empenalo.test",
    category: "otro",
    brand: "Sony",
    model: "PlayStation 5 Slim",
    year: 2024,
    storage: "1 TB",
    condition: "Nuevo",
    description: "Sellada. Doble joystick. 2 juegos.",
    expected_amount_pen: 1900,
    expected_term_days: 30,
    district: "Miraflores",
    status: "active",
  },
  {
    client_email: "cliente8@empenalo.test",
    category: "otro",
    brand: "Microsoft",
    model: "Xbox Series X",
    year: 2023,
    storage: "1 TB",
    condition: "Bueno",
    description: "Con cargador y 1 mando adicional.",
    expected_amount_pen: 1500,
    expected_term_days: 30,
    district: "Surquillo",
    status: "active",
  },
  {
    client_email: "cliente2@empenalo.test",
    category: "otro",
    brand: "Nintendo",
    model: "Switch OLED",
    year: 2022,
    storage: "64 GB",
    condition: "Bueno",
    description: "Pantalla impecable. Con dock y juegos.",
    expected_amount_pen: 950,
    expected_term_days: 30,
    district: "San Isidro",
    status: "active",
  },

  // ── instrumento → otro (2) ────────────────────────────────────────────────
  {
    client_email: "cliente7@empenalo.test",
    category: "otro",
    brand: "Fender",
    model: "Stratocaster American Pro II",
    year: 2022,
    storage: null,
    condition: "Bueno",
    description: "Guitarra eléctrica con case original.",
    expected_amount_pen: 4500,
    expected_term_days: 60,
    district: "Barranco",
    status: "active",
  },
  {
    client_email: "cliente4@empenalo.test",
    category: "otro",
    brand: "Yamaha",
    model: "Piano digital P-125",
    year: 2021,
    storage: null,
    condition: "Bueno",
    description: "Con soporte y pedal sustain.",
    expected_amount_pen: 1800,
    expected_term_days: 45,
    district: "San Borja",
    status: "active",
  },

  // ── bicicleta → otro (2) ──────────────────────────────────────────────────
  {
    client_email: "cliente1@empenalo.test",
    category: "otro",
    brand: "Specialized",
    model: "Stumpjumper Comp Alloy",
    year: 2023,
    storage: null,
    condition: "Bueno",
    description: "MTB doble suspensión talla M. Componentes Shimano XT.",
    expected_amount_pen: 5800,
    expected_term_days: 60,
    district: "Miraflores",
    status: "active",
  },
  {
    client_email: "cliente5@empenalo.test",
    category: "otro",
    brand: "Trek",
    model: "Domane SL 5",
    year: 2022,
    storage: null,
    condition: "Bueno",
    description: "Ruta. Carbón. Talla 54.",
    expected_amount_pen: 4200,
    expected_term_days: 60,
    district: "La Molina",
    status: "active",
  },

  // ── herramienta → otro (2) ────────────────────────────────────────────────
  {
    client_email: "cliente8@empenalo.test",
    category: "otro",
    brand: "DeWalt",
    model: "Kit combo 20V MAX (10 piezas)",
    year: 2023,
    storage: null,
    condition: "Bueno",
    description: "Profesional. Maletín completo con baterías.",
    expected_amount_pen: 1600,
    expected_term_days: 30,
    district: "Surquillo",
    status: "active",
  },
  {
    client_email: "cliente3@empenalo.test",
    category: "otro",
    brand: "Bosch",
    model: "Rotomartillo profesional GBH 2-26",
    year: 2022,
    storage: null,
    condition: "Regular",
    description: "Funcional. Cable con cinta aislante.",
    expected_amount_pen: 550,
    expected_term_days: 30,
    district: "Santiago de Surco",
    status: "active",
  },

  // ── camara → otro (2) ─────────────────────────────────────────────────────
  {
    client_email: "cliente6@empenalo.test",
    category: "otro",
    brand: "Sony",
    model: "Alpha A7 IV",
    year: 2023,
    storage: null,
    condition: "Bueno",
    description: "Cuerpo + lente 28-70mm. 12k disparos.",
    expected_amount_pen: 7200,
    expected_term_days: 60,
    district: "Miraflores",
    status: "accepted",
  },
  {
    client_email: "cliente2@empenalo.test",
    category: "otro",
    brand: "Canon",
    model: "EOS R6 Mark II",
    year: 2023,
    storage: null,
    condition: "Nuevo",
    description: "Solo cuerpo. Caja y accesorios.",
    expected_amount_pen: 6800,
    expected_term_days: 60,
    district: "San Isidro",
    status: "expired",
  },

  // ── otro (2) ─────────────────────────────────────────────────────────────
  {
    client_email: "cliente7@empenalo.test",
    category: "otro",
    brand: "Louis Vuitton",
    model: "Bolso Neverfull MM",
    year: 2022,
    storage: null,
    condition: "Bueno",
    description: "Bolso original con datecode. Polvera incluida.",
    expected_amount_pen: 2400,
    expected_term_days: 45,
    district: "Barranco",
    status: "active",
  },
  {
    client_email: "cliente4@empenalo.test",
    category: "otro",
    brand: null,
    model: "Drone DJI Mavic 3 Pro",
    year: 2023,
    storage: null,
    condition: "Nuevo",
    description: "Combo Fly More. 3 baterías. Sellado.",
    expected_amount_pen: 4500,
    expected_term_days: 45,
    district: "San Borja",
    status: "active",
  },
];
