/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as NegocioRouteImport } from './routes/negocio'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as AppRouteImport } from './routes/app'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NegocioIndexRouteImport } from './routes/negocio.index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as NegocioVerifyRouteImport } from './routes/negocio.verify'
import { Route as NegocioSolicitudesRouteImport } from './routes/negocio.solicitudes'
import { Route as NegocioSolicitudRouteImport } from './routes/negocio.solicitud'
import { Route as NegocioRegisterRouteImport } from './routes/negocio.register'
import { Route as NegocioPropuestasRouteImport } from './routes/negocio.propuestas'
import { Route as NegocioPropuestaRouteImport } from './routes/negocio.propuesta'
import { Route as NegocioPlanRouteImport } from './routes/negocio.plan'
import { Route as NegocioPerfilRouteImport } from './routes/negocio.perfil'
import { Route as NegocioNotificationsRouteImport } from './routes/negocio.notifications'
import { Route as NegocioLoginRouteImport } from './routes/negocio.login'
import { Route as NegocioHistorialRouteImport } from './routes/negocio.historial'
import { Route as NegocioForgotPasswordRouteImport } from './routes/negocio.forgot-password'
import { Route as NegocioDashboardRouteImport } from './routes/negocio.dashboard'
import { Route as AppVerifyRouteImport } from './routes/app.verify'
import { Route as AppRegisterRouteImport } from './routes/app.register'
import { Route as AppPublishedRouteImport } from './routes/app.published'
import { Route as AppPublishRouteImport } from './routes/app.publish'
import { Route as AppProposalsRouteImport } from './routes/app.proposals'
import { Route as AppProposalDetailRouteImport } from './routes/app.proposal-detail'
import { Route as AppNotificationsRouteImport } from './routes/app.notifications'
import { Route as AppMisArticulosRouteImport } from './routes/app.mis-articulos'
import { Route as AppLoginRouteImport } from './routes/app.login'
import { Route as AppHistoryRouteImport } from './routes/app.history'
import { Route as AppForgotPasswordRouteImport } from './routes/app.forgot-password'
import { Route as AppDashboardRouteImport } from './routes/app.dashboard'
import { Route as AppCuentaRouteImport } from './routes/app.cuenta'
import { Route as AppCodeRouteImport } from './routes/app.code'
import { Route as ApiCulqiWebhookRouteImport } from './routes/api.culqi-webhook'

const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const NegocioRoute = NegocioRouteImport.update({
  id: '/negocio',
  path: '/negocio',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NegocioIndexRoute = NegocioIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => NegocioRoute,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const NegocioVerifyRoute = NegocioVerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => NegocioRoute,
} as any)
const NegocioSolicitudesRoute = NegocioSolicitudesRouteImport.update({
  id: '/solicitudes',
  path: '/solicitudes',
  getParentRoute: () => NegocioRoute,
} as any)
const NegocioSolicitudRoute = NegocioSolicitudRouteImport.update({
  id: '/solicitud',
  path: '/solicitud',
  getParentRoute: () => NegocioRoute,
} as any)
const NegocioRegisterRoute = NegocioRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => NegocioRoute,
} as any)
const NegocioPropuestasRoute = NegocioPropuestasRouteImport.update({
  id: '/propuestas',
  path: '/propuestas',
  getParentRoute: () => NegocioRoute,
} as any)
const NegocioPropuestaRoute = NegocioPropuestaRouteImport.update({
  id: '/propuesta',
  path: '/propuesta',
  getParentRoute: () => NegocioRoute,
} as any)
const NegocioPlanRoute = NegocioPlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => NegocioRoute,
} as any)
const NegocioPerfilRoute = NegocioPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => NegocioRoute,
} as any)
const NegocioNotificationsRoute = NegocioNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => NegocioRoute,
} as any)
const NegocioLoginRoute = NegocioLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => NegocioRoute,
} as any)
const NegocioHistorialRoute = NegocioHistorialRouteImport.update({
  id: '/historial',
  path: '/historial',
  getParentRoute: () => NegocioRoute,
} as any)
const NegocioForgotPasswordRoute = NegocioForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => NegocioRoute,
} as any)
const NegocioDashboardRoute = NegocioDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => NegocioRoute,
} as any)
const AppVerifyRoute = AppVerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => AppRoute,
} as any)
const AppRegisterRoute = AppRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AppRoute,
} as any)
const AppPublishedRoute = AppPublishedRouteImport.update({
  id: '/published',
  path: '/published',
  getParentRoute: () => AppRoute,
} as any)
const AppPublishRoute = AppPublishRouteImport.update({
  id: '/publish',
  path: '/publish',
  getParentRoute: () => AppRoute,
} as any)
const AppProposalsRoute = AppProposalsRouteImport.update({
  id: '/proposals',
  path: '/proposals',
  getParentRoute: () => AppRoute,
} as any)
const AppProposalDetailRoute = AppProposalDetailRouteImport.update({
  id: '/proposal-detail',
  path: '/proposal-detail',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppMisArticulosRoute = AppMisArticulosRouteImport.update({
  id: '/mis-articulos',
  path: '/mis-articulos',
  getParentRoute: () => AppRoute,
} as any)
const AppLoginRoute = AppLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AppRoute,
} as any)
const AppHistoryRoute = AppHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AppRoute,
} as any)
const AppForgotPasswordRoute = AppForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCuentaRoute = AppCuentaRouteImport.update({
  id: '/cuenta',
  path: '/cuenta',
  getParentRoute: () => AppRoute,
} as any)
const AppCodeRoute = AppCodeRouteImport.update({
  id: '/code',
  path: '/code',
  getParentRoute: () => AppRoute,
} as any)
const ApiCulqiWebhookRoute = ApiCulqiWebhookRouteImport.update({
  id: '/api/culqi-webhook',
  path: '/api/culqi-webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/app': typeof AppRouteWithChildren
  '/faq': typeof FaqRoute
  '/negocio': typeof NegocioRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/api/culqi-webhook': typeof ApiCulqiWebhookRoute
  '/app/code': typeof AppCodeRoute
  '/app/cuenta': typeof AppCuentaRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/forgot-password': typeof AppForgotPasswordRoute
  '/app/history': typeof AppHistoryRoute
  '/app/login': typeof AppLoginRoute
  '/app/mis-articulos': typeof AppMisArticulosRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/proposal-detail': typeof AppProposalDetailRoute
  '/app/proposals': typeof AppProposalsRoute
  '/app/publish': typeof AppPublishRoute
  '/app/published': typeof AppPublishedRoute
  '/app/register': typeof AppRegisterRoute
  '/app/verify': typeof AppVerifyRoute
  '/negocio/dashboard': typeof NegocioDashboardRoute
  '/negocio/forgot-password': typeof NegocioForgotPasswordRoute
  '/negocio/historial': typeof NegocioHistorialRoute
  '/negocio/login': typeof NegocioLoginRoute
  '/negocio/notifications': typeof NegocioNotificationsRoute
  '/negocio/perfil': typeof NegocioPerfilRoute
  '/negocio/plan': typeof NegocioPlanRoute
  '/negocio/propuesta': typeof NegocioPropuestaRoute
  '/negocio/propuestas': typeof NegocioPropuestasRoute
  '/negocio/register': typeof NegocioRegisterRoute
  '/negocio/solicitud': typeof NegocioSolicitudRoute
  '/negocio/solicitudes': typeof NegocioSolicitudesRoute
  '/negocio/verify': typeof NegocioVerifyRoute
  '/app/': typeof AppIndexRoute
  '/negocio/': typeof NegocioIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/faq': typeof FaqRoute
  '/privacy': typeof PrivacyRoute
  '/api/culqi-webhook': typeof ApiCulqiWebhookRoute
  '/app/code': typeof AppCodeRoute
  '/app/cuenta': typeof AppCuentaRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/forgot-password': typeof AppForgotPasswordRoute
  '/app/history': typeof AppHistoryRoute
  '/app/login': typeof AppLoginRoute
  '/app/mis-articulos': typeof AppMisArticulosRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/proposal-detail': typeof AppProposalDetailRoute
  '/app/proposals': typeof AppProposalsRoute
  '/app/publish': typeof AppPublishRoute
  '/app/published': typeof AppPublishedRoute
  '/app/register': typeof AppRegisterRoute
  '/app/verify': typeof AppVerifyRoute
  '/negocio/dashboard': typeof NegocioDashboardRoute
  '/negocio/forgot-password': typeof NegocioForgotPasswordRoute
  '/negocio/historial': typeof NegocioHistorialRoute
  '/negocio/login': typeof NegocioLoginRoute
  '/negocio/notifications': typeof NegocioNotificationsRoute
  '/negocio/perfil': typeof NegocioPerfilRoute
  '/negocio/plan': typeof NegocioPlanRoute
  '/negocio/propuesta': typeof NegocioPropuestaRoute
  '/negocio/propuestas': typeof NegocioPropuestasRoute
  '/negocio/register': typeof NegocioRegisterRoute
  '/negocio/solicitud': typeof NegocioSolicitudRoute
  '/negocio/solicitudes': typeof NegocioSolicitudesRoute
  '/negocio/verify': typeof NegocioVerifyRoute
  '/app': typeof AppIndexRoute
  '/negocio': typeof NegocioIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/app': typeof AppRouteWithChildren
  '/faq': typeof FaqRoute
  '/negocio': typeof NegocioRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/api/culqi-webhook': typeof ApiCulqiWebhookRoute
  '/app/code': typeof AppCodeRoute
  '/app/cuenta': typeof AppCuentaRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/forgot-password': typeof AppForgotPasswordRoute
  '/app/history': typeof AppHistoryRoute
  '/app/login': typeof AppLoginRoute
  '/app/mis-articulos': typeof AppMisArticulosRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/proposal-detail': typeof AppProposalDetailRoute
  '/app/proposals': typeof AppProposalsRoute
  '/app/publish': typeof AppPublishRoute
  '/app/published': typeof AppPublishedRoute
  '/app/register': typeof AppRegisterRoute
  '/app/verify': typeof AppVerifyRoute
  '/negocio/dashboard': typeof NegocioDashboardRoute
  '/negocio/forgot-password': typeof NegocioForgotPasswordRoute
  '/negocio/historial': typeof NegocioHistorialRoute
  '/negocio/login': typeof NegocioLoginRoute
  '/negocio/notifications': typeof NegocioNotificationsRoute
  '/negocio/perfil': typeof NegocioPerfilRoute
  '/negocio/plan': typeof NegocioPlanRoute
  '/negocio/propuesta': typeof NegocioPropuestaRoute
  '/negocio/propuestas': typeof NegocioPropuestasRoute
  '/negocio/register': typeof NegocioRegisterRoute
  '/negocio/solicitud': typeof NegocioSolicitudRoute
  '/negocio/solicitudes': typeof NegocioSolicitudesRoute
  '/negocio/verify': typeof NegocioVerifyRoute
  '/app/': typeof AppIndexRoute
  '/negocio/': typeof NegocioIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/app'
    | '/faq'
    | '/negocio'
    | '/privacy'
    | '/api/culqi-webhook'
    | '/app/code'
    | '/app/cuenta'
    | '/app/dashboard'
    | '/app/forgot-password'
    | '/app/history'
    | '/app/login'
    | '/app/mis-articulos'
    | '/app/notifications'
    | '/app/proposal-detail'
    | '/app/proposals'
    | '/app/publish'
    | '/app/published'
    | '/app/register'
    | '/app/verify'
    | '/negocio/dashboard'
    | '/negocio/forgot-password'
    | '/negocio/historial'
    | '/negocio/login'
    | '/negocio/notifications'
    | '/negocio/perfil'
    | '/negocio/plan'
    | '/negocio/propuesta'
    | '/negocio/propuestas'
    | '/negocio/register'
    | '/negocio/solicitud'
    | '/negocio/solicitudes'
    | '/negocio/verify'
    | '/app/'
    | '/negocio/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/faq'
    | '/privacy'
    | '/api/culqi-webhook'
    | '/app/code'
    | '/app/cuenta'
    | '/app/dashboard'
    | '/app/forgot-password'
    | '/app/history'
    | '/app/login'
    | '/app/mis-articulos'
    | '/app/notifications'
    | '/app/proposal-detail'
    | '/app/proposals'
    | '/app/publish'
    | '/app/published'
    | '/app/register'
    | '/app/verify'
    | '/negocio/dashboard'
    | '/negocio/forgot-password'
    | '/negocio/historial'
    | '/negocio/login'
    | '/negocio/notifications'
    | '/negocio/perfil'
    | '/negocio/plan'
    | '/negocio/propuesta'
    | '/negocio/propuestas'
    | '/negocio/register'
    | '/negocio/solicitud'
    | '/negocio/solicitudes'
    | '/negocio/verify'
    | '/app'
    | '/negocio'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/app'
    | '/faq'
    | '/negocio'
    | '/privacy'
    | '/api/culqi-webhook'
    | '/app/code'
    | '/app/cuenta'
    | '/app/dashboard'
    | '/app/forgot-password'
    | '/app/history'
    | '/app/login'
    | '/app/mis-articulos'
    | '/app/notifications'
    | '/app/proposal-detail'
    | '/app/proposals'
    | '/app/publish'
    | '/app/published'
    | '/app/register'
    | '/app/verify'
    | '/negocio/dashboard'
    | '/negocio/forgot-password'
    | '/negocio/historial'
    | '/negocio/login'
    | '/negocio/notifications'
    | '/negocio/perfil'
    | '/negocio/plan'
    | '/negocio/propuesta'
    | '/negocio/propuestas'
    | '/negocio/register'
    | '/negocio/solicitud'
    | '/negocio/solicitudes'
    | '/negocio/verify'
    | '/app/'
    | '/negocio/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AppRoute: typeof AppRouteWithChildren
  FaqRoute: typeof FaqRoute
  NegocioRoute: typeof NegocioRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
  ApiCulqiWebhookRoute: typeof ApiCulqiWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/negocio': {
      id: '/negocio'
      path: '/negocio'
      fullPath: '/negocio'
      preLoaderRoute: typeof NegocioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/negocio/': {
      id: '/negocio/'
      path: '/'
      fullPath: '/negocio/'
      preLoaderRoute: typeof NegocioIndexRouteImport
      parentRoute: typeof NegocioRoute
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/negocio/verify': {
      id: '/negocio/verify'
      path: '/verify'
      fullPath: '/negocio/verify'
      preLoaderRoute: typeof NegocioVerifyRouteImport
      parentRoute: typeof NegocioRoute
    }
    '/negocio/solicitudes': {
      id: '/negocio/solicitudes'
      path: '/solicitudes'
      fullPath: '/negocio/solicitudes'
      preLoaderRoute: typeof NegocioSolicitudesRouteImport
      parentRoute: typeof NegocioRoute
    }
    '/negocio/solicitud': {
      id: '/negocio/solicitud'
      path: '/solicitud'
      fullPath: '/negocio/solicitud'
      preLoaderRoute: typeof NegocioSolicitudRouteImport
      parentRoute: typeof NegocioRoute
    }
    '/negocio/register': {
      id: '/negocio/register'
      path: '/register'
      fullPath: '/negocio/register'
      preLoaderRoute: typeof NegocioRegisterRouteImport
      parentRoute: typeof NegocioRoute
    }
    '/negocio/propuestas': {
      id: '/negocio/propuestas'
      path: '/propuestas'
      fullPath: '/negocio/propuestas'
      preLoaderRoute: typeof NegocioPropuestasRouteImport
      parentRoute: typeof NegocioRoute
    }
    '/negocio/propuesta': {
      id: '/negocio/propuesta'
      path: '/propuesta'
      fullPath: '/negocio/propuesta'
      preLoaderRoute: typeof NegocioPropuestaRouteImport
      parentRoute: typeof NegocioRoute
    }
    '/negocio/plan': {
      id: '/negocio/plan'
      path: '/plan'
      fullPath: '/negocio/plan'
      preLoaderRoute: typeof NegocioPlanRouteImport
      parentRoute: typeof NegocioRoute
    }
    '/negocio/perfil': {
      id: '/negocio/perfil'
      path: '/perfil'
      fullPath: '/negocio/perfil'
      preLoaderRoute: typeof NegocioPerfilRouteImport
      parentRoute: typeof NegocioRoute
    }
    '/negocio/notifications': {
      id: '/negocio/notifications'
      path: '/notifications'
      fullPath: '/negocio/notifications'
      preLoaderRoute: typeof NegocioNotificationsRouteImport
      parentRoute: typeof NegocioRoute
    }
    '/negocio/login': {
      id: '/negocio/login'
      path: '/login'
      fullPath: '/negocio/login'
      preLoaderRoute: typeof NegocioLoginRouteImport
      parentRoute: typeof NegocioRoute
    }
    '/negocio/historial': {
      id: '/negocio/historial'
      path: '/historial'
      fullPath: '/negocio/historial'
      preLoaderRoute: typeof NegocioHistorialRouteImport
      parentRoute: typeof NegocioRoute
    }
    '/negocio/forgot-password': {
      id: '/negocio/forgot-password'
      path: '/forgot-password'
      fullPath: '/negocio/forgot-password'
      preLoaderRoute: typeof NegocioForgotPasswordRouteImport
      parentRoute: typeof NegocioRoute
    }
    '/negocio/dashboard': {
      id: '/negocio/dashboard'
      path: '/dashboard'
      fullPath: '/negocio/dashboard'
      preLoaderRoute: typeof NegocioDashboardRouteImport
      parentRoute: typeof NegocioRoute
    }
    '/app/verify': {
      id: '/app/verify'
      path: '/verify'
      fullPath: '/app/verify'
      preLoaderRoute: typeof AppVerifyRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/register': {
      id: '/app/register'
      path: '/register'
      fullPath: '/app/register'
      preLoaderRoute: typeof AppRegisterRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/published': {
      id: '/app/published'
      path: '/published'
      fullPath: '/app/published'
      preLoaderRoute: typeof AppPublishedRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/publish': {
      id: '/app/publish'
      path: '/publish'
      fullPath: '/app/publish'
      preLoaderRoute: typeof AppPublishRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/proposals': {
      id: '/app/proposals'
      path: '/proposals'
      fullPath: '/app/proposals'
      preLoaderRoute: typeof AppProposalsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/proposal-detail': {
      id: '/app/proposal-detail'
      path: '/proposal-detail'
      fullPath: '/app/proposal-detail'
      preLoaderRoute: typeof AppProposalDetailRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/notifications': {
      id: '/app/notifications'
      path: '/notifications'
      fullPath: '/app/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/mis-articulos': {
      id: '/app/mis-articulos'
      path: '/mis-articulos'
      fullPath: '/app/mis-articulos'
      preLoaderRoute: typeof AppMisArticulosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/login': {
      id: '/app/login'
      path: '/login'
      fullPath: '/app/login'
      preLoaderRoute: typeof AppLoginRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/history': {
      id: '/app/history'
      path: '/history'
      fullPath: '/app/history'
      preLoaderRoute: typeof AppHistoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/forgot-password': {
      id: '/app/forgot-password'
      path: '/forgot-password'
      fullPath: '/app/forgot-password'
      preLoaderRoute: typeof AppForgotPasswordRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/cuenta': {
      id: '/app/cuenta'
      path: '/cuenta'
      fullPath: '/app/cuenta'
      preLoaderRoute: typeof AppCuentaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/code': {
      id: '/app/code'
      path: '/code'
      fullPath: '/app/code'
      preLoaderRoute: typeof AppCodeRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/culqi-webhook': {
      id: '/api/culqi-webhook'
      path: '/api/culqi-webhook'
      fullPath: '/api/culqi-webhook'
      preLoaderRoute: typeof ApiCulqiWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppCodeRoute: typeof AppCodeRoute
  AppCuentaRoute: typeof AppCuentaRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppForgotPasswordRoute: typeof AppForgotPasswordRoute
  AppHistoryRoute: typeof AppHistoryRoute
  AppLoginRoute: typeof AppLoginRoute
  AppMisArticulosRoute: typeof AppMisArticulosRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppProposalDetailRoute: typeof AppProposalDetailRoute
  AppProposalsRoute: typeof AppProposalsRoute
  AppPublishRoute: typeof AppPublishRoute
  AppPublishedRoute: typeof AppPublishedRoute
  AppRegisterRoute: typeof AppRegisterRoute
  AppVerifyRoute: typeof AppVerifyRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCodeRoute: AppCodeRoute,
  AppCuentaRoute: AppCuentaRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppForgotPasswordRoute: AppForgotPasswordRoute,
  AppHistoryRoute: AppHistoryRoute,
  AppLoginRoute: AppLoginRoute,
  AppMisArticulosRoute: AppMisArticulosRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppProposalDetailRoute: AppProposalDetailRoute,
  AppProposalsRoute: AppProposalsRoute,
  AppPublishRoute: AppPublishRoute,
  AppPublishedRoute: AppPublishedRoute,
  AppRegisterRoute: AppRegisterRoute,
  AppVerifyRoute: AppVerifyRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface NegocioRouteChildren {
  NegocioDashboardRoute: typeof NegocioDashboardRoute
  NegocioForgotPasswordRoute: typeof NegocioForgotPasswordRoute
  NegocioHistorialRoute: typeof NegocioHistorialRoute
  NegocioLoginRoute: typeof NegocioLoginRoute
  NegocioNotificationsRoute: typeof NegocioNotificationsRoute
  NegocioPerfilRoute: typeof NegocioPerfilRoute
  NegocioPlanRoute: typeof NegocioPlanRoute
  NegocioPropuestaRoute: typeof NegocioPropuestaRoute
  NegocioPropuestasRoute: typeof NegocioPropuestasRoute
  NegocioRegisterRoute: typeof NegocioRegisterRoute
  NegocioSolicitudRoute: typeof NegocioSolicitudRoute
  NegocioSolicitudesRoute: typeof NegocioSolicitudesRoute
  NegocioVerifyRoute: typeof NegocioVerifyRoute
  NegocioIndexRoute: typeof NegocioIndexRoute
}

const NegocioRouteChildren: NegocioRouteChildren = {
  NegocioDashboardRoute: NegocioDashboardRoute,
  NegocioForgotPasswordRoute: NegocioForgotPasswordRoute,
  NegocioHistorialRoute: NegocioHistorialRoute,
  NegocioLoginRoute: NegocioLoginRoute,
  NegocioNotificationsRoute: NegocioNotificationsRoute,
  NegocioPerfilRoute: NegocioPerfilRoute,
  NegocioPlanRoute: NegocioPlanRoute,
  NegocioPropuestaRoute: NegocioPropuestaRoute,
  NegocioPropuestasRoute: NegocioPropuestasRoute,
  NegocioRegisterRoute: NegocioRegisterRoute,
  NegocioSolicitudRoute: NegocioSolicitudRoute,
  NegocioSolicitudesRoute: NegocioSolicitudesRoute,
  NegocioVerifyRoute: NegocioVerifyRoute,
  NegocioIndexRoute: NegocioIndexRoute,
}

const NegocioRouteWithChildren =
  NegocioRoute._addFileChildren(NegocioRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AppRoute: AppRouteWithChildren,
  FaqRoute: FaqRoute,
  NegocioRoute: NegocioRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
  ApiCulqiWebhookRoute: ApiCulqiWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
